<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsdl="http://www.de4a.eu/2020/wsdl" xmlns:req="http://www.de4a.eu/2020/data/evaluator/pattern/usi" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" targetNamespace="http://www.de4a.eu/2020/wsdl">
	<types>
		<xsd:schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.de4a.eu/2020/data/evaluator/pattern/usi" schemaLocation="DE1-USI.xsd"/>
		</xsd:schema>
	</types>
	<message name="requestForwardEvidence">
		<part name="RequestForwardEvidence" element="req:RequestForwardEvidence"/>
	</message>
	<message name="responseForwardEvidence">
		<part name="ResponseForwardEvidence" element="req:ResponseForwardEvidence"/>
	</message>
	<portType name="ForwardEvidencePortType">
		<operation name="requestForwardEvidence">
			<input message="wsdl:requestForwardEvidence"/>
			<output message="wsdl:responseForwardEvidence"/>
		</operation>
	</portType>
	<binding name="ForwardEvidenceBinding" type="wsdl:ForwardEvidencePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="requestForwardEvidence">
			<soap:operation soapAction="responseForwardEvidence" style="document"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="DataEvaluator.USI">
		<port name="DataEvaluator.USI" binding="wsdl:ForwardEvidenceBinding">
			<soap:address location="https://de4a.redsara.es/DataEvaluator/USI"/>
		</port>
	</service>
</definitions>
