<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsdl="http://www.de4a.eu/2020/wsdl" xmlns:req="http://www.de4a.eu/2020/data/requestor/idk" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" targetNamespace="http://www.de4a.eu/2020/wsdl">
	<types>
		<xsd:schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.de4a.eu/2020/data/requestor/idk" schemaLocation="DR1-IDK.xsd"/>
		</xsd:schema>
	</types>
	<message name="requestLookupRoutingInformation">
		<part name="RequestLookupRoutingInformation" element="req:RequestLookupRoutingInformation"/>
	</message>
	<message name="responseLookupRoutingInformation">
		<part name="ResponseLookupRoutingInformation" element="req:ResponseLookupRoutingInformation"/>
	</message>
	<message name="requestLookupEvidenceServiceData">
		<part name="RequestLookupEvidenceServiceData" element="req:RequestLookupEvidenceServiceData"/>
	</message>
	<message name="responseLookupEvidenceServiceData">
		<part name="ResponseLookupEvidenceServiceData" element="req:ResponseLookupEvidenceServiceData"/>
	</message>
	<portType name="LookupPortType">
		<operation name="requestLookupRoutingInformation">
			<input message="wsdl:requestLookupRoutingInformation"/>
			<output message="wsdl:responseLookupRoutingInformation"/>
		</operation>
		<operation name="requestLookupEvidenceServiceData">
			<input message="wsdl:requestLookupEvidenceServiceData"/>
			<output message="wsdl:responseLookupEvidenceServiceData"/>
		</operation>
	</portType>
	<binding name="LookupIDKBinding" type="wsdl:LookupPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="requestLookupRoutingInformation">
			<soap:operation soapAction="requestLookupRoutingInformation" style="document"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
		<operation name="requestLookupEvidenceServiceData">
			<soap:operation soapAction="requestLookupEvidenceServiceData" style="document"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="DataRequestor.IDK">
		<port name="DataRequestor.IDK" binding="wsdl:LookupIDKBinding">
			<soap:address location="https://de4a.redsara.es/DataRequestor/IDK"/>
		</port>
	</service>
</definitions>
